{{- $sinkConfig := include "rastreo.sinkConfig" . }}
{{- if $sinkConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rastreo.fullname" . }}-sink
  labels:
    {{- include "rastreo.labels" . | nindent 4 }}
data:
  sink.yaml: |
    {{- $sinkConfig | nindent 4 }}
{{- end }}
