{{- if and .Values.auth.enabled .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rastreo.fullname" . }}-auth
  labels:
    {{- include "rastreo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
{{- if and (or .Values.otlp.metricsEnabled .Values.otlp.logsEnabled .Values.otlp.tracesEnabled) .Values.otlp.headers (not .Values.otlp.headersExistingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rastreo.fullname" . }}-otlp
  labels:
    {{- include "rastreo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.otlp.headersSecretKey }}: {{ .Values.otlp.headers | quote }}
{{- end }}
