[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rastreo-core = { path = "../rastreo-core", features = ["kafka", "http", "snmp", "lldp", "arp", "ndp", "oui", "nats", "ssh", "icmp", "tls", "gnmi"] }
schemars = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tonic-prost-build = "0.14"
tempfile = { workspace = true }
