//! Single source of truth for the observable `rastreo_server_*` metrics: name, help, kind,
//! labels, and value-reader are defined once and generated by both the Prometheus text encoder
//! and the OTLP instrument registrar. A metric is present exactly when its reader emits at least
//! one sample, which is how the conditional sink-reachability series omit themselves when no sink
//! is configured. The OTLP side probes each reader once at startup, so a conditional metric must
//! gate on startup-fixed state — a reader empty at boot but non-empty later would be dropped from
//! OTLP. The `scan_duration_seconds` histogram is special-cased on both sides and is not part of
//! this table.

use std::sync::atomic::Ordering;

use rastreo_core::{ProbeKind, SinkErrorClass, SinkType};

use crate::state::{Metrics, SinkReachability};

pub(crate) enum MetricValue {
    U64(u64),
    F64(f64),
}

pub(crate) enum MetricKind {
    CounterU64,
    GaugeU64,
    GaugeF64,
}

impl MetricKind {
    pub(crate) fn prometheus_type(&self) -> &'static str {
        match self {
            MetricKind::CounterU64 => "counter",
            MetricKind::GaugeU64 | MetricKind::GaugeF64 => "gauge",
        }
    }
}

pub(crate) type Label = (&'static str, &'static str);

pub(crate) type SampleSink<'a> = dyn FnMut(&[Label], MetricValue) + 'a;

pub(crate) struct MetricContext<'a> {
    pub metrics: &'a Metrics,
    pub reachability: &'a SinkReachability,
}

pub(crate) struct MetricDescriptor {
    pub name: &'static str,
    pub help: &'static str,
    pub kind: MetricKind,
    pub read: fn(&MetricContext, &mut SampleSink),
}

pub(crate) fn descriptors() -> &'static [MetricDescriptor] {
    &DESCRIPTORS
}

static DESCRIPTORS: [MetricDescriptor; 9] = [
    MetricDescriptor {
        name: "rastreo_server_scans_total",
        help: "POST /scans requests served, partitioned by outcome.",
        kind: MetricKind::CounterU64,
        read: read_scans_total,
    },
    MetricDescriptor {
        name: "rastreo_server_probes_total",
        help: "Probes executed across all scans, partitioned by outcome and probe kind.",
        kind: MetricKind::CounterU64,
        read: read_probes_total,
    },
    MetricDescriptor {
        name: "rastreo_server_records_emitted_total",
        help: "DeviceRecords emitted across all scans.",
        kind: MetricKind::CounterU64,
        read: read_records_emitted_total,
    },
    MetricDescriptor {
        name: "rastreo_server_sink_errors_total",
        help: "Internal sink errors surfaced via POST /scans, partitioned by error class.",
        kind: MetricKind::CounterU64,
        read: read_sink_errors_total,
    },
    MetricDescriptor {
        name: "rastreo_server_dlq_records_total",
        help: "Records delivered to a dead-letter destination, partitioned by sink type and error class.",
        kind: MetricKind::CounterU64,
        read: read_dlq_records_total,
    },
    MetricDescriptor {
        name: "rastreo_server_sink_reachability_probe_total",
        help: "Server-side sink reachability probes, partitioned by outcome and sink type.",
        kind: MetricKind::CounterU64,
        read: read_sink_reachability_probe_total,
    },
    MetricDescriptor {
        name: "rastreo_server_sink_reachable",
        help: "1 when the last sink probe succeeded, 0 otherwise.",
        kind: MetricKind::GaugeU64,
        read: read_sink_reachable,
    },
    MetricDescriptor {
        name: "rastreo_server_uptime_seconds",
        help: "Seconds since rastreo-server started.",
        kind: MetricKind::GaugeF64,
        read: read_uptime_seconds,
    },
    MetricDescriptor {
        name: "rastreo_server_build_info",
        help: "Build info (version label always 1).",
        kind: MetricKind::GaugeU64,
        read: read_build_info,
    },
];

fn read_scans_total(ctx: &MetricContext, emit: &mut SampleSink) {
    let m = ctx.metrics;
    emit(
        &[("outcome", "success")],
        MetricValue::U64(m.scans_total_success.load(Ordering::Relaxed)),
    );
    emit(
        &[("outcome", "error")],
        MetricValue::U64(m.scans_total_error.load(Ordering::Relaxed)),
    );
    emit(
        &[("outcome", "cancelled")],
        MetricValue::U64(m.scans_total_cancelled.load(Ordering::Relaxed)),
    );
}

fn read_probes_total(ctx: &MetricContext, emit: &mut SampleSink) {
    let m = ctx.metrics;
    for kind in ProbeKind::all() {
        let idx = kind.index();
        let label = kind.label();
        emit(
            &[("outcome", "success"), ("probe_kind", label)],
            MetricValue::U64(m.probes.succeeded[idx].load(Ordering::Relaxed)),
        );
        emit(
            &[("outcome", "error"), ("probe_kind", label)],
            MetricValue::U64(m.probes.errored[idx].load(Ordering::Relaxed)),
        );
    }
}

fn read_records_emitted_total(ctx: &MetricContext, emit: &mut SampleSink) {
    emit(
        &[],
        MetricValue::U64(ctx.metrics.records_emitted_total.load(Ordering::Relaxed)),
    );
}

fn read_sink_errors_total(ctx: &MetricContext, emit: &mut SampleSink) {
    let m = ctx.metrics;
    for class in SinkErrorClass::all() {
        emit(
            &[("error_class", class.as_label())],
            MetricValue::U64(m.sink_errors[class.index()].load(Ordering::Relaxed)),
        );
    }
}

fn read_dlq_records_total(ctx: &MetricContext, emit: &mut SampleSink) {
    let m = ctx.metrics;
    for (sink, bucket) in [
        (SinkType::Kafka, &m.dlq.kafka),
        (SinkType::Nats, &m.dlq.nats),
    ] {
        for class in SinkErrorClass::all() {
            emit(
                &[
                    ("sink_type", sink.as_label()),
                    ("error_class", class.as_label()),
                ],
                MetricValue::U64(bucket[class.index()].load(Ordering::Relaxed)),
            );
        }
    }
}

fn read_sink_reachability_probe_total(ctx: &MetricContext, emit: &mut SampleSink) {
    let Some(sink_label) = ctx.reachability.sink_type_label() else {
        return;
    };
    let m = ctx.metrics;
    emit(
        &[("outcome", "success"), ("sink_type", sink_label)],
        MetricValue::U64(m.sink_probe_success.load(Ordering::Relaxed)),
    );
    emit(
        &[("outcome", "failure"), ("sink_type", sink_label)],
        MetricValue::U64(m.sink_probe_failure.load(Ordering::Relaxed)),
    );
}

fn read_sink_reachable(ctx: &MetricContext, emit: &mut SampleSink) {
    let Some(sink_label) = ctx.reachability.sink_type_label() else {
        return;
    };
    let value: u64 = ctx.reachability.reachable.load(Ordering::Relaxed).into();
    emit(&[("sink_type", sink_label)], MetricValue::U64(value));
}

fn read_uptime_seconds(ctx: &MetricContext, emit: &mut SampleSink) {
    emit(
        &[],
        MetricValue::F64(ctx.metrics.started_at.elapsed().as_secs_f64()),
    );
}

fn read_build_info(_ctx: &MetricContext, emit: &mut SampleSink) {
    emit(
        &[("version", env!("CARGO_PKG_VERSION"))],
        MetricValue::U64(1),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    use std::time::Duration;

    use crate::state::SinkReachability;

    const CONDITIONAL: [&str; 2] = [
        "rastreo_server_sink_reachability_probe_total",
        "rastreo_server_sink_reachable",
    ];

    fn descriptor(name: &str) -> &'static MetricDescriptor {
        descriptors()
            .iter()
            .find(|d| d.name == name)
            .expect("descriptor exists")
    }

    fn sample_count(desc: &MetricDescriptor, ctx: &MetricContext) -> usize {
        let mut count = 0;
        (desc.read)(ctx, &mut |_, _| count += 1);
        count
    }

    #[test]
    fn descriptor_names_are_unique() {
        let mut names: Vec<&str> = descriptors().iter().map(|d| d.name).collect();
        let total = names.len();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), total, "descriptor names must be unique");
    }

    #[test]
    fn conditional_readers_emit_nothing_without_a_configured_sink() {
        let metrics = Metrics::new();
        let reachability = SinkReachability::not_configured();
        let ctx = MetricContext {
            metrics: &metrics,
            reachability: &reachability,
        };
        for name in CONDITIONAL {
            assert_eq!(
                sample_count(descriptor(name), &ctx),
                0,
                "{name} must emit no samples without a sink"
            );
        }
    }

    #[test]
    fn conditional_readers_emit_samples_with_a_configured_sink() {
        let metrics = Metrics::new();
        let reachability = SinkReachability::configured(
            SinkType::Kafka,
            Duration::from_secs(10),
            Duration::from_secs(5),
        );
        let ctx = MetricContext {
            metrics: &metrics,
            reachability: &reachability,
        };
        assert_eq!(
            sample_count(
                descriptor("rastreo_server_sink_reachability_probe_total"),
                &ctx
            ),
            2
        );
        assert_eq!(
            sample_count(descriptor("rastreo_server_sink_reachable"), &ctx),
            1
        );
    }

    #[test]
    fn non_conditional_readers_always_emit_at_least_one_sample() {
        let metrics = Metrics::new();
        let reachability = SinkReachability::not_configured();
        let ctx = MetricContext {
            metrics: &metrics,
            reachability: &reachability,
        };
        for desc in descriptors() {
            if CONDITIONAL.contains(&desc.name) {
                continue;
            }
            assert!(
                sample_count(desc, &ctx) > 0,
                "{} must always emit at least one sample",
                desc.name
            );
        }
    }
}
